development:
  adapter: postgresql
  encoding: unicode
  database: kix_development
  host: localhost

test:
  adapter: postgresql
  encoding: unicode
  database: kix_test
  host: localhost

stagin:
  adapter: postgresql
  encoding: unicode
  database: staging_production
  host: localhost

production:
  adapter: postgresql
  encoding: unicode
  database: kix_production
  host: localhost
